apiVersion: apps/v1
kind: Deployment
metadata:
  name: cts-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cts-backend
  template:
    metadata:
      labels:
        app: cts-backend
    spec:
      containers:
      - name: cts-backend
        image: 658658/cts-backend:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10

