name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt

    - name: Test application
      run: |
        # Add your test commands here, e.g., using unittest
        echo "No tests specified"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/cts-backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.21.0'

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up gcloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'

    - name: Add Google Cloud SDK repository and install gke-gcloud-auth-plugin
      run: |
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
        sudo apt-get install -y apt-transport-https ca-certificates gnupg
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
        sudo apt-get update && sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

    - name: Create .kube directory
      run: |
        mkdir -p $HOME/.kube

    - name: Set up Kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yml
        kubectl apply -f k8s/service.yml
        kubectl apply -f k8s/hpa.yml
        kubectl apply -f k8s/ingress.yml

    - name: Check pods
      run: |
        kubectl get all

    - name: Wait for ingress to get external IP
      run: |
        echo "Waiting for ingress external IP..."
        for i in {1..30}; do
          INGRESS_IP=$(kubectl get ingress cts-backend-ingress -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          if [ -n "$INGRESS_IP" ]; then
            echo "Ingress external IP: $INGRESS_IP"
            break
          fi
          echo "Retrying in 10 seconds..."
          sleep 10
        done
        if [ -z "$INGRESS_IP" ]; then
          echo "Ingress external IP not found"
          exit 1
        fi

    - name: Update /etc/hosts
      run: |
        echo "$INGRESS_IP cts-example.com" | sudo tee -a /etc/hosts    
        
    - name: Check service availability
      run: |
        sleep 30 # Wait for the service to be available
        curl -f http://cts-example.com/ping

